GET http://localhost:4444

###

POST http://localhost:4444/init
Content-Type: application/json

{
    "secret": "12345",
    "adminpassword": "cisco"
}

###

POST http://localhost:4444/login
Content-Type: application/json

{
    "username": "admin",
    "password": "cisco"
}

###
PUT http://localhost:4444/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicnVvbG8iOiJhZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzMzNzUzODQzLCJleHAiOjE3MzM3NTc0NDN9.2ApzZUZ_lxmr4vfVFerN7cIp-1NBZAtURUsoYU1aZ3o
Content-Type: application/json
{
    "id": 1,
    "nome": "Skibidi"
}
###
GET http://localhost:4444/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicnVvbG8iOiJhZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzMzNzUzODQzLCJleHAiOjE3MzM3NTc0NDN9.2ApzZUZ_lxmr4vfVFerN7cIp-1NBZAtURUsoYU1aZ3o

# POST http://localhost:4444/users
# Authorization: 
GET http://localhost:4444/users/1

###
DELETE http://localhost:4444/users/1
